res.send(Buffer.from('whoop'))
res.send({ some: 'json' })
res.send('<p>http//localhost:3000</p>')
res.status(404).send('Sorry, we cannot find that!')
res.status(500).send({ error: 'something blew up' })